# Generated by Django 4.0.5 on 2022-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicals',
            name='Number',
            field=models.IntegerField(),
        ),
    ]
