# Generated by Django 4.0.5 on 2022-08-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_medicals_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicals',
            name='photo',
        ),
    ]
