# Generated by Django 4.0.5 on 2022-08-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_medicals_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicals',
            name='Message',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medicals',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
